### ISSUE TITLE
Documentation: how to install/test QWERTYUIOPYOZO's version?

### ISSUE THREAD

**Issue by ohthehugemanatee** [haxiomic/firefox-multi-touch-zoom#20]
I see in the AMO description that @QWERTYUIOPYOZO has developed a version that may work on Windows touch devices. I have a surface pro; I'd like to test it and report back... but I can't find any instructions for how to install from his fork.

**Comment by QWERTYUIOPYOZO** [comment]
Wow, great timing. Just went to check this.
It has been merged into the main extension.
You can test it by downloading the extension on AMO.

**Comment by QWERTYUIOPYOZO** [comment]
If you want to install from my fork (which is exactly the same as the one on AMO), zip up the contents in the extension folder, go to about:debugging in firefox, hit "load temporary addon" and select your zip.

**Comment by ohthehugemanatee** [comment]
Well then! I guess I already have the right version. It seems to work well, the only exception is gmaps. But I understand they hijack the 2 finger behavior?

Thank you for the lightning-fast response, the good instructions, and the hard work!

**Comment by QWERTYUIOPYOZO** [comment]
Thanks to you for testing it!
