### ISSUE TITLE
–MacOS 10.14 Mojave.– Not working on Firefox, but working on Waterfox and Tor browser

### ISSUE THREAD

**Issue by InVItroVeritas** [haxiomic/firefox-multi-touch-zoom#26]
The add-on only works when I'm holding down command, alt or shift. I installed it a while ago and in the beginning I think it worked for a short while but it then stopped. 

The suspicious thing is that it does work –without having to hold down any modifier key– on Waterfox and Tor browser, which are both modified versions of Firefox . Tested all on the same pages. This makes me believe it should be possible to have the add-on work properly on Firefox. 

The about:config parameters (which didn't work in the first place) are all to its default mode. I even “refreshed” Firefox to see if the add-on would work, but it still doesn't. 

I am on version 63.0.1 (64-bit) of Firefox. 56.2.5 (64-bit) of Waterfox. And 8.0.3 (based on Mozilla Firefox 60.3.0esr) (64-bit) of Tor browser. 

On MacOS 10.14 Mojave.

Do you have any idea why the add-on might not be work and what I could do to fix it?

**Comment by haxiomic** [comment]
Hey @InVItroVeritas, I've just tested FF 63.0.1 on Mojave and it's working for me. It's interesting the other FF variants work.

To debug this: try disabling the add-on on FF 63 and then try and pinch-zoom on [google maps](https://www.google.com/maps). Does that work? Or do you need to hold one of the modifier keys to make it work?

**Comment by InVItroVeritas** [comment]
> To debug this: try disabling the add-on on FF 63 and then try and pinch-zoom on [google maps](https://www.google.com/maps). Does that work? Or do you need to hold one of the modifier keys to make it work?

It doesn't work  on google maps without holding down one of the modifier keys.

**Comment by haxiomic** [comment]
Cool, that implies that it's not something specific to this add-on but something going on with your Firefox install (pinching on google maps should work), but it's a mystery as to what has changed to require the modifier key to zoom.

My best guess is it's something in `about:config`, if you click on the `status` column header you can order by `modified` and see any non-defaults

If you've not got any settings you mind about you could do a fresh install by first removing with [AppCleaner](https://freemacsoft.net/appcleaner/) (or equivalent – mainly we want to remove `~/Library/Application Support/Firefox` and `~/Library/Caches/Firefox`)

It's worth launching in Safe Mode to confirm that it's not another addon causing the issue: https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode

Finally, check your trackpad setting in system preferences to confirm pinch-zoom is enabled

**Comment by InVItroVeritas** [comment]
I think I have figured it out. Apparently it was the Better Touch Tool app that for some reason was interfering with Firefox but not the other browsers. That's why resetting it completely didn't work. 

Just disabling and re-enabling the BTT app seems to have fixed it. 

Thanks for the help.

**Comment by haxiomic** [comment]
Ahh, nice one pin pointing the issue. Yeah now it’s resolved I’ll close the issue :)
