### ISSUE TITLE
No option to disable zooming while "shift" is pressed on multi-touch trackpads

### ISSUE THREAD

**Issue by themindstorm** [haxiomic/firefox-multi-touch-zoom#30]
Macbooks have multi-touch trackpads, so there is no need to hold shift and scroll to zoom. However, there is no option to disable the "shift" action. Am I missing a setting?

**Comment by haxiomic** [comment]
Good point, this is a small change so I’ll add it to the settings page, thanks for suggesting :)

**Comment by franky47** [comment]
Also it could help with #5, which is annoying on Macbooks as well due to inertial scrolling caught by the Shift key.

**Comment by haxiomic** [comment]
Fixed by @AkdM
