### ISSUE TITLE
Scrolls instead of zooming on some sites

### ISSUE THREAD

**Issue by matatk** [haxiomic/firefox-multi-touch-zoom#31]
When using this extension on most sites, pinching does indeed perform a zoom. However, recently, https://www.macrumors.com scrolls vertically rather than zooming.

Perhaps this is related to #29.

Thanks for this extension; it enabled me to switch back to Firefox :-).

**Comment by haxiomic** [comment]
Good spot @matatk, thanks for reporting – I've looked into it and turns out to be because that page has CSS that overrides the `transform` applied to the root element. We should be able to fix by override by adding `!important`. I've scheduled sometime to make some fixes this week

**Comment by haxiomic** [comment]
Fixed in 6f14840552f1d11fb6564380d8a13098452af65d

**Comment by matatk** [comment]
Thanks @haxiomic, the update has come through and is working very well :-).
