### ISSUE TITLE
Not working in `about:` pages

### ISSUE THREAD

**Issue by rajdeepbharati** [haxiomic/firefox-multi-touch-zoom#32]
If I go to an `about` page like `about:addons` or `about:preferences` in firefox then the zoom isn't working using the mac trackpad. Also, it isn't working for https://addons.mozilla.org/

Here's my [browser and system specification](whatsmybrowser.org/b/EALU762)

**Comment by haxiomic** [comment]
Hey @rajdeepbharati, all addons are disabled on certain pages, including addons.mozilla.org to prevent malicious addons making themselves difficult to remove.

This is a feature of the browser and not something that can be changed
