### ISSUE TITLE
Causes grey site for Mastodon

### ISSUE THREAD

**Issue by rugk** [haxiomic/firefox-multi-touch-zoom#33]
See https://github.com/tootsuite/mastodon/issues/10056

In short the `transform` with values of "1" seems to cause it to have a grey page.

**Comment by haxiomic** [comment]
@rugk, so transforms where scale x and y are not 1 work?

If that’s the case then it should work if we remove the transform when scale is 1 (since that is equivalent to no scale)

**Comment by rugk** [comment]
Yes, if I zoom in via touch, it works. (and if I zoom out afterwards)

But if I only scroll (which adds scale x and y = 1) it somehow gets all grey.

**Comment by haxiomic** [comment]
@rugk does this still happen with the latest version? I can't reproduce it anymore, may have been a change in 0.7 or a change on mastodon

**Comment by rugk** [comment]
Sorry, but I do not use this software anymore, so I could not test it. I'll just assume it works now, if you say so, and close this issue.

**Comment by haxiomic** [comment]
Thanks @rugk :)
