### ISSUE TITLE
Moving left/right just after zooming in or out triggers back/forward page, instead of moving around the page.

### ISSUE THREAD

**Issue by ys27** [haxiomic/firefox-multi-touch-zoom#35]
Moving left/right just after zooming in or out triggers back/forward page, instead of moving around the page.

To replicate, 

1. go to page that has a page to go back to.
2. zoom in or out with two fingers.
3. Try to move around using two fingers right after zoom. It will start to trigger the back or forward page load.

It would be ideal to start moving around the page.

Thank you.

**Comment by haxiomic** [comment]
Hey @ys27, I've just uploaded version 0.9 to the [addons page](https://addons.mozilla.org/en-GB/firefox/addon/multi-touch-zoom/)

It adds a new setting **"Disable scrollbars when zooming"**, if you uncheck this it should solve your issue

That behaviour was originally added because it improve zoom performance a lot, however when I test in recent versions of Firefox the performance problems seem to have gone. I'm keen to hear if you find performance any different with that feature disabled

**Comment by ys27** [comment]
Hi, thanks for the quick update! I updated to 0.9 and unchecked the 'disable scrollbars when zooming' option, but the same back/forward are triggered and I am unable to scroll sideways right away. I tried this after restarting Firefox completely and with the macbook trackpad and the external magic trackpad 2. I don't seem to notice any performance differences. Thank you!

**Comment by haxiomic** [comment]
@ys27 that's interesting, are the scrollbars visible when zooming like in this gif? It could be that the setting isn't taking affect

![Screen Recording 2019-06-10 at 15 17 54](https://user-images.githubusercontent.com/3742992/59201798-1e850c00-8b93-11e9-9d6d-50cef309688b.gif)

**Comment by ys27** [comment]
@haxiomic No, I don't see the scrollbars while zooming. They're not visible for both settings (on and off).

**Comment by haxiomic** [comment]
Ahh, ok that implies the setting isn't working for you. Don't know why but I'll investigate :)

**Comment by haxiomic** [comment]
@ys27 Do the other settings work like zoom speed?

**Comment by ys27** [comment]
@haxiomic Oh, they don't seem to work. The zoom speeds are the same no matter the setting, and I am able to shift + scroll with the setting unchecked.

**Comment by haxiomic** [comment]
@ys27, not sure why settings aren't working for you but I've just submitted a new version, 0.95 that uses local storage rather than cloud-sync to save preferences. Let me know if your settings issue is solved in that version

**Comment by ys27** [comment]
@haxiomic That fixed it! It seems that I have to exit Firefox and restart for the settings to take effect, but all the settings now work and the scroll issue is resolved as well. Thank you for your quick help!

**Comment by haxiomic** [comment]
Yey :) 🎉
