### ISSUE TITLE
Fail on 2 key sites

### ISSUE THREAD

**Issue by esysfound** [haxiomic/firefox-multi-touch-zoom#37]
Not working on New York Times (nytimes.com) or Financial Times (ft.com).  The whole point for me.
Have set all Firefox pinch zoom settings both as you suggest (empty) or using defaults.  No difference.

What can be done?  Thanks

**Comment by haxiomic** [comment]
Hey @esysfound, what happens if you hold shift and scroll down?

Does pinch-zoom work on other websites such as https://bbc.co.uk/news?

I've just updated my version of Firefox and it seems to have stopped the extension working on all websites (including normal pinch zoom in google maps), maybe this is related to your issue – which version of Firefox are you using?

**Comment by esysfound** [comment]
Hi

Thanks for writing back - as I mentioned am running FF 68.0.1 (64bit)
Pinch-well actually 2 figured verticle up and down works for me on Google Maps. but almost nothing else. Not the Beeb..
Shift +scroll only zoom in, cannot zoom out.
It is a mess.
But Normal (built in) Cntl + and Cntl- works fine.

Shame as your app is really needed.

Let me know if you can sort it.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by haxiomic** [comment]
Sounds like the same issue I’m having, I think something has changed in Firefox recently which has disabled  the pinch gesture (you should be able to two-finger pinch in google maps (not only  two finger scroll) like you can in Chrome

I’ll look into it but at this point I don’t think it’s something I can fix from within the extension

**Comment by esysfound** [comment]
Maybe you should contact Mozilla?
They might explain what may have changed
and potentially how to respond so the addon works again?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by haxiomic** [comment]
I'm not sure my comment update came through via email – after restarting the pinch gesture is now working for me

Are you running macOS? If not what OS?

To rule out system touch settings, what happens when you try to pinch-zoom on https://maps.google.com from Chrome?

**Comment by esysfound** [comment]
Hi-no, running Windows.

What do you mean, "restarting"?
And are you on Windows or macOS?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by esysfound** [comment]
Sorry - yes in Chrome,  google maps zooms on pinch (and 2 finger scroll)

running Windows 10 64 bit, newest build 1903

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by haxiomic** [comment]
If it works in google maps in Chrome and not FF that indicates it's not a system level issue but rather a Windows Firefox issue

I don't have a windows setup with a touchscreen or trackpad to work with

25% of the extension users are on Windows so hopefully we'll have more insight if other people start reporting the same issue

(I'm on macOS, and by restarting I just mean rebooting)
