### ISSUE TITLE
Scroll bars appear in full screen on Youtube

### ISSUE THREAD

**Issue by Eirifix** [haxiomic/firefox-multi-touch-zoom#40]
Scroll bars appear in full screen on Youtube on my Surface Pro's when this extension is enabled.
It used to work fine but then Youtube changed something. This makes me have to disable the extension and only enable it when I really need it. It used to work just like touch zoom in Chrome.

**Comment by haxiomic** [comment]
What happens when you press Ctrl + 0?

**Comment by Eirifix** [comment]
They disappear, thanks, but I am actually only using touch on the Surface Pro. It would be great if it was possible to have a gesture like a 3 finger double tap to do the same. Youtube also bugs out sometimes when the extension is activated (seems like the video is zoomed way in) but I think this would solve that as well.

**Comment by haxiomic** [comment]
Ahh got you, yeah they should disappear when you zoom all the way out - I'll look into fixing this

**Comment by Eirifix** [comment]
That would be great. I really prefer Firefox over Chrome and your extension fixed the only downside of using Firefox, especially on a touch system.

**Comment by haxiomic** [comment]
I've just tried the latest firefox and it looks like native zooming has arrived in the browser
I'm on Firefox 69, first disable my plugin, then go to `about:config` in the URL set `apz.allow_zooming` to true

Let me know if that works better :)

**Comment by Eirifix** [comment]
That works perfectly! Thanks a lot 👍
