### ISSUE TITLE
Magic Mouse (inertial scrolling) and the shift key

### ISSUE THREAD

**Issue by ealimonda** [haxiomic/firefox-multi-touch-zoom#5]
When using the Magic Mouse (or any mouse with inertial scrolling), if you press the Shift key while a scroll action is in progress, you get unwanted zoom events. If this was resolved (i.e. ignoring any shift-scroll events if the shift key wasn't pressed before the scroll started), this addon would be really awesome.

Steps to reproduce:

- Have a Magic Mouse or another inertial-scrolling device connected
- Load a zoomable webpage, preferably a very long one such as https://bugzilla.mozilla.org/show_bug.cgi?id=688990
- Scroll through the page with large swipes on the MM surface
- Stop swiping and while the page still scrolls with inertia, press the shift key (i.e. as part of the shift-cmd-tab shortcut)
- See the page that zooms in (or out depending on the scroll direction) on its own

Either way, it'd be nice to have a setting to disable the shift-scroll functionality, and only zoom with the pinch gesture (because this issue can be triggered even without inertial scrolling, although less frequently)

**Comment by haxiomic** [comment]
Hey @ealimonda, thanks for reporting – good spot! I'd not noticed the inertial scrolling carries into zoom when you press shift. At the very least I'll add some settings to disable shift-scroll but I'll also see if there's a way to prevent the inertial scroll splitting over

**Comment by chamini2** [comment]
close, right?

**Comment by haxiomic** [comment]
@chamini2 yep, let’s close this now.

Option was added to disable shift scroll in v0.7
