### ISSUE TITLE
Working on touchpad, but not on touchscreen

### ISSUE THREAD

**Issue by aublick** [haxiomic/firefox-multi-touch-zoom#8]
I am using Surface 4 and when using pinch to zoom on touchpad, the extension works reasonably well. However, when I try to zoom content by pinching it on the touchscreen, it does not work at all, and instead it changes the zoom percentage of the website.

**Comment by lyneca** [comment]
+1, same on Arch Linux

**Comment by KrasnayaPloshchad** [comment]
Yes, same on Windows 10 and Lenovo Yoga

**Comment by QWERTYUIOPYOZO** [comment]
Sent in pull request to fix issue.

> 15

**Comment by KrasnayaPloshchad** [comment]
OK, this is fixed
