### ISSUE TITLE
Choose a project license

### ISSUE THREAD

**Issue by rschiang** [haxiomic/firefox-multi-touch-zoom#9]
Adding a [copyright license](https://choosealicense.com/) to the project would enable collaborators to contribute to the project freely.

It is recommended to use MIT (for more permissive use) or GPLv3 (for the advocacy of software freedom) 🎈

**Comment by haxiomic** [comment]
Good point, thanks for highlighting. I'll go with MIT (but tempted by the WTFPL license ;)

**Comment by haxiomic** [comment]
2237cb920f8a9021f4d97408095b43fcb7ecee8d
